interface AudioBookDetailsInfo {

    approval_status: number,
    author_name: string,
    banner_path: null,
    category_id: null,
    channel_id: number,
    contributing_artists: string,
    created_at: string,
    deleted: number,
    description: string,
    discount_price: number,
    for_app: number,
    guid: string,
    id: number,
    name: string,
    en_name: null,
    play_count: number,
    podcast: number,
    premium: number,
    price: number,
    publish_year: null,
    thumb_path: string,
    updated_at: Date,
    c_name: null,
    file_name: null,
    file_path: string,
    rating: number,
    rating_count: number,
    user_rating: number,
    review: string,
    is_favorite: false,
    episodes: Array<any>,
}
export default AudioBookDetailsInfo;